# Generated by Django 6.0.5 on 2026-05-27 20:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('entreprises', '0001_initial'),
        ('sites_rh', '0001_initial'),
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='entreprise',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='utilisateurs', to='entreprises.entreprise'),
        ),
        migrations.AddField(
            model_name='user',
            name='site',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='utilisateurs', to='sites_rh.site'),
        ),
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('super_admin', 'Super Administrateur'), ('dg', 'Directeur Général'), ('drh', 'Directeur RH'), ('responsable_rh', 'Responsable RH'), ('gestionnaire_paie', 'Gestionnaire Paie'), ('responsable_site', 'Responsable Site'), ('chef_unite', 'Chef Unité Production'), ('superviseur', 'Superviseur Sécurité'), ('chef_equipe', 'Chef Équipe'), ('secretaire_rh', 'Secrétaire RH'), ('employe', 'Employé / Agent')], default='employe', max_length=30),
        ),
    ]
