# Generated by Django 6.0.5 on 2026-05-27 20:53

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('entreprises', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Site',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=200)),
                ('code', models.CharField(max_length=20, unique=True)),
                ('type_site', models.CharField(choices=[('siege', 'Siège social'), ('usine', 'Usine / Production'), ('agence', 'Agence'), ('chantier', 'Chantier'), ('poste_securite', 'Poste de sécurité'), ('entrepot', 'Entrepôt'), ('autre', 'Autre')], default='agence', max_length=30)),
                ('adresse', models.TextField(blank=True)),
                ('ville', models.CharField(blank=True, max_length=100)),
                ('latitude', models.DecimalField(blank=True, decimal_places=7, max_digits=10, null=True)),
                ('longitude', models.DecimalField(blank=True, decimal_places=7, max_digits=10, null=True)),
                ('rayon_geofence', models.IntegerField(default=100, help_text='Rayon autorisé en mètres pour le pointage GPS')),
                ('telephone', models.CharField(blank=True, max_length=20)),
                ('est_actif', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('entreprise', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sites', to='entreprises.entreprise')),
                ('responsable', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sites_geres', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Site',
                'verbose_name_plural': 'Sites',
                'ordering': ['entreprise', 'nom'],
            },
        ),
        migrations.CreateModel(
            name='Unite',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=150)),
                ('code', models.CharField(blank=True, max_length=20)),
                ('type_unite', models.CharField(choices=[('departement', 'Département'), ('ligne_production', 'Ligne de production'), ('equipe', 'Équipe'), ('service', 'Service'), ('poste_garde', 'Poste de garde')], default='departement', max_length=30)),
                ('description', models.TextField(blank=True)),
                ('capacite_max', models.IntegerField(default=0, help_text="Nombre max d'agents")),
                ('est_actif', models.BooleanField(default=True)),
                ('responsable', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='unites_gerees', to=settings.AUTH_USER_MODEL)),
                ('site', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='unites', to='sites_rh.site')),
            ],
            options={
                'verbose_name': 'Unité',
                'verbose_name_plural': 'Unités',
                'ordering': ['site', 'nom'],
            },
        ),
    ]
