# Generated by Django 6.0.5 on 2026-05-27 20:53

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('employes', '0003_ficheposte_departement_site_employe_banque_and_more'),
        ('planning', '0001_initial'),
        ('sites_rh', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Pointage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type_pointage', models.CharField(choices=[('entree', 'Entrée'), ('sortie', 'Sortie')], max_length=10)),
                ('mode', models.CharField(choices=[('smartphone', 'Smartphone agent'), ('tablette_superviseur', 'Tablette superviseur'), ('qrcode', 'QR Code'), ('biometrie', 'Biométrie'), ('manuel', 'Saisie manuelle')], default='smartphone', max_length=30)),
                ('datetime_pointage', models.DateTimeField()),
                ('date_pointage', models.DateField()),
                ('latitude', models.DecimalField(blank=True, decimal_places=7, max_digits=10, null=True)),
                ('longitude', models.DecimalField(blank=True, decimal_places=7, max_digits=10, null=True)),
                ('precision_gps', models.FloatField(blank=True, help_text='Précision GPS en mètres', null=True)),
                ('distance_du_site', models.FloatField(blank=True, help_text='Distance calculée au site en mètres', null=True)),
                ('dans_geofence', models.BooleanField(default=True)),
                ('device_id', models.CharField(blank=True, max_length=200)),
                ('device_imei', models.CharField(blank=True, max_length=100)),
                ('device_correspond', models.BooleanField(default=True, help_text="L'appareil correspond au device enregistré")),
                ('gps_mock_detecte', models.BooleanField(default=False)),
                ('photo_selfie', models.ImageField(blank=True, null=True, upload_to='pointages/selfies/')),
                ('statut', models.CharField(choices=[('valide', 'Valide'), ('anomalie', 'Anomalie'), ('en_attente', 'En attente validation'), ('rejete', 'Rejeté')], default='valide', max_length=20)),
                ('anomalie_description', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('employe', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pointages', to='employes.employe')),
                ('ligne_planning', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='planning.ligneplanning')),
                ('pointe_par', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pointages_effectues', to=settings.AUTH_USER_MODEL)),
                ('shift_prevu', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='planning.typeshift')),
                ('site', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='sites_rh.site')),
                ('valide_par', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pointages_valides', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Pointage',
                'verbose_name_plural': 'Pointages',
                'ordering': ['-datetime_pointage'],
            },
        ),
        migrations.CreateModel(
            name='AnomaliePointage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type_anomalie', models.CharField(choices=[('hors_zone', 'Hors zone GPS'), ('device_inconnu', 'Appareil inconnu'), ('gps_mock', 'GPS simulé'), ('double_pointage', 'Double pointage'), ('retard', 'Retard'), ('absence', 'Absence'), ('depart_anticipe', 'Départ anticipé')], max_length=30)),
                ('date', models.DateField()),
                ('description', models.TextField()),
                ('statut', models.CharField(choices=[('non_traite', 'Non traité'), ('justifie', 'Justifié'), ('non_justifie', 'Non justifié')], default='non_traite', max_length=20)),
                ('justification', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('employe', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='anomalies_pointage', to='employes.employe')),
                ('traite_par', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('pointage', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='anomalies', to='pointage.pointage')),
            ],
            options={
                'verbose_name': 'Anomalie pointage',
                'verbose_name_plural': 'Anomalies pointage',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='pointage',
            index=models.Index(fields=['employe', 'date_pointage'], name='pointage_po_employe_63aa08_idx'),
        ),
        migrations.AddIndex(
            model_name='pointage',
            index=models.Index(fields=['site', 'date_pointage'], name='pointage_po_site_id_0891f6_idx'),
        ),
    ]
