# Generated by Django 6.0.5 on 2026-05-28 09:21

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pointage', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='pointage',
            name='correction_par',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='corrections_effectuees', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='pointage',
            name='datetime_correction',
            field=models.DateTimeField(blank=True, help_text='Heure corrigée par admin', null=True),
        ),
        migrations.AddField(
            model_name='pointage',
            name='note_correction',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='pointage',
            name='note_superviseur',
            field=models.TextField(blank=True, help_text='Note justificative du superviseur'),
        ),
    ]
