# Generated by Django 6.0.5 on 2026-05-27 20:53

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Entreprise',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=200)),
                ('sigle', models.CharField(blank=True, max_length=20)),
                ('logo', models.ImageField(blank=True, null=True, upload_to='entreprises/logos/')),
                ('secteur', models.CharField(choices=[('securite', 'Sécurité / Gardiennage'), ('industrie', 'Industrie / Usine'), ('services', 'Services'), ('commerce', 'Commerce'), ('sante', 'Santé'), ('education', 'Éducation'), ('btp', 'BTP / Construction'), ('autre', 'Autre')], default='services', max_length=30)),
                ('rccm', models.CharField(blank=True, max_length=50, verbose_name='N° RCCM')),
                ('ncc', models.CharField(blank=True, max_length=50, verbose_name='N° NCC')),
                ('telephone', models.CharField(blank=True, max_length=20)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('adresse', models.TextField(blank=True)),
                ('ville', models.CharField(blank=True, max_length=100)),
                ('pays', models.CharField(default="Côte d'Ivoire", max_length=100)),
                ('est_actif', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Entreprise',
                'verbose_name_plural': 'Entreprises',
                'ordering': ['nom'],
            },
        ),
    ]
