# Generated by Django 6.0.5 on 2026-05-27 20:53

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('documents', '0001_initial'),
        ('employes', '0003_ficheposte_departement_site_employe_banque_and_more'),
        ('entreprises', '0001_initial'),
        ('sites_rh', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='EvenementCarriere',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type_evenement', models.CharField(choices=[('recrutement', 'Recrutement'), ('promotion', 'Promotion'), ('mutation', 'Mutation'), ('changement_poste', 'Changement de poste'), ('augmentation_salaire', 'Augmentation de salaire'), ('renouvellement_contrat', 'Renouvellement de contrat'), ('changement_contrat', 'Changement de type contrat'), ('suspension', 'Suspension'), ('reprise', 'Reprise de service'), ('demission', 'Démission'), ('licenciement', 'Licenciement'), ('depart_retraite', 'Départ à la retraite'), ('sanction', 'Sanction disciplinaire'), ('formation', 'Formation'), ('evaluation', 'Évaluation de performance')], max_length=30)),
                ('date_evenement', models.DateField()),
                ('date_effet', models.DateField(help_text="Date d'entrée en vigueur")),
                ('description', models.TextField()),
                ('salaire_avant', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('salaire_apres', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('approuve_par', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='validations_carrieres', to=settings.AUTH_USER_MODEL)),
                ('document', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='documents.document')),
                ('employe', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='evenements_carriere', to='employes.employe')),
                ('poste_apres', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='employes.poste')),
                ('poste_avant', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='employes.poste')),
                ('site_apres', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='sites_rh.site')),
                ('site_avant', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='sites_rh.site')),
            ],
            options={
                'verbose_name': 'Événement carrière',
                'verbose_name_plural': 'Événements carrière',
                'ordering': ['-date_evenement'],
            },
        ),
        migrations.CreateModel(
            name='RegleEvolutionCarriere',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=150)),
                ('anciennete_min_annees', models.IntegerField(default=0)),
                ('est_actif', models.BooleanField(default=True)),
                ('notification_auto', models.BooleanField(default=True)),
                ('entreprise', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='entreprises.entreprise')),
                ('poste_actuel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='regles_evolution_depart', to='employes.poste')),
                ('poste_cible', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='regles_evolution_cible', to='employes.poste')),
            ],
            options={
                'verbose_name': 'Règle évolution carrière',
                'verbose_name_plural': 'Règles évolution carrière',
            },
        ),
    ]
