# Generated by Django 6.0.5 on 2026-05-27 20:53

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('employes', '0003_ficheposte_departement_site_employe_banque_and_more'),
        ('entreprises', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ParametreHeures',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('heures_normales_jour', models.DecimalField(decimal_places=2, default=8, max_digits=4)),
                ('heures_max_journalier', models.DecimalField(decimal_places=2, default=12, max_digits=4)),
                ('heure_debut_nuit', models.TimeField(default='22:00')),
                ('heure_fin_nuit', models.TimeField(default='06:00')),
                ('taux_majoration_nuit', models.DecimalField(decimal_places=2, default=15, max_digits=5)),
                ('taux_majoration_supp_25', models.DecimalField(decimal_places=2, default=25, help_text='Supp 1-8h', max_digits=5)),
                ('taux_majoration_supp_50', models.DecimalField(decimal_places=2, default=50, help_text='Supp >8h', max_digits=5)),
                ('taux_majoration_dimanche', models.DecimalField(decimal_places=2, default=30, max_digits=5)),
                ('taux_majoration_ferie', models.DecimalField(decimal_places=2, default=100, max_digits=5)),
                ('tolerance_retard_minutes', models.IntegerField(default=5)),
                ('entreprise', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='parametres_heures', to='entreprises.entreprise')),
            ],
            options={
                'verbose_name': 'Paramètre heures',
                'verbose_name_plural': 'Paramètres heures',
            },
        ),
        migrations.CreateModel(
            name='RecapHeures',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('annee', models.IntegerField()),
                ('mois', models.IntegerField()),
                ('heures_normales', models.DecimalField(decimal_places=2, default=0, max_digits=7)),
                ('heures_nuit', models.DecimalField(decimal_places=2, default=0, max_digits=7)),
                ('heures_supp_25', models.DecimalField(decimal_places=2, default=0, help_text='Majorées à 25%', max_digits=7)),
                ('heures_supp_50', models.DecimalField(decimal_places=2, default=0, help_text='Majorées à 50%', max_digits=7)),
                ('heures_dimanche', models.DecimalField(decimal_places=2, default=0, max_digits=7)),
                ('heures_ferie', models.DecimalField(decimal_places=2, default=0, max_digits=7)),
                ('jours_travailles', models.IntegerField(default=0)),
                ('jours_absents', models.IntegerField(default=0)),
                ('jours_conge', models.IntegerField(default=0)),
                ('retards_count', models.IntegerField(default=0)),
                ('retards_minutes_total', models.IntegerField(default=0)),
                ('montant_heures_normales', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('montant_heures_nuit', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('montant_heures_supp', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('montant_absences_deduites', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('calcule_le', models.DateTimeField(auto_now=True)),
                ('valide', models.BooleanField(default=False)),
                ('employe', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recaps_heures', to='employes.employe')),
                ('valide_par', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Récap heures',
                'verbose_name_plural': 'Récaps heures',
                'ordering': ['-annee', '-mois'],
                'unique_together': {('employe', 'annee', 'mois')},
            },
        ),
    ]
