# Generated by Django 6.0.5 on 2026-05-27 20:53

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('employes', '0003_ficheposte_departement_site_employe_banque_and_more'),
        ('planning', '0001_initial'),
        ('pointage', '0001_initial'),
        ('sites_rh', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='JourFerie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(unique=True)),
                ('nom', models.CharField(max_length=100)),
                ('pays', models.CharField(default='CI', max_length=50)),
                ('est_national', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Jour férié',
                'verbose_name_plural': 'Jours fériés',
                'ordering': ['date'],
            },
        ),
        migrations.CreateModel(
            name='RapportPresence',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('periode', models.CharField(choices=[('jour', 'Journalier'), ('semaine', 'Hebdomadaire'), ('mois', 'Mensuel')], default='mois', max_length=10)),
                ('date_debut', models.DateField()),
                ('date_fin', models.DateField()),
                ('total_employes', models.IntegerField(default=0)),
                ('presents', models.IntegerField(default=0)),
                ('retards', models.IntegerField(default=0)),
                ('absents_justifies', models.IntegerField(default=0)),
                ('absents_non_justifies', models.IntegerField(default=0)),
                ('taux_presence', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('heures_total', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('heures_nuit_total', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('heures_supp_total', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('genere_le', models.DateTimeField(auto_now_add=True)),
                ('site', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sites_rh.site')),
            ],
            options={
                'verbose_name': 'Rapport de présence',
                'verbose_name_plural': 'Rapports de présence',
            },
        ),
        migrations.CreateModel(
            name='Presence',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('statut', models.CharField(choices=[('present', 'Présent'), ('retard', 'Présent avec retard'), ('absent_justifie', 'Absent justifié'), ('absent_non_justifie', 'Absent non justifié'), ('conge', 'En congé'), ('maladie', 'Maladie'), ('mission', 'En mission'), ('permission', 'Permission'), ('formation', 'Formation'), ('ferie', 'Jour férié'), ('repos', 'Repos planifié'), ('suspension', 'Suspension')], default='present', max_length=30)),
                ('heure_arrivee', models.TimeField(blank=True, null=True)),
                ('heure_depart', models.TimeField(blank=True, null=True)),
                ('retard_minutes', models.IntegerField(default=0)),
                ('depart_anticipe_minutes', models.IntegerField(default=0)),
                ('heures_travaillees', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('heures_nuit', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('heures_supp', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('justification', models.TextField(blank=True)),
                ('calcul_automatique', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('employe', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='presences', to='employes.employe')),
                ('justifie_par', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('pointage_entree', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='presence_entree', to='pointage.pointage')),
                ('pointage_sortie', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='presence_sortie', to='pointage.pointage')),
                ('shift', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='planning.typeshift')),
                ('site', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='sites_rh.site')),
            ],
            options={
                'verbose_name': 'Présence',
                'verbose_name_plural': 'Présences',
                'ordering': ['-date', 'employe__nom'],
                'indexes': [models.Index(fields=['date', 'statut'], name='presences_p_date_3fd72f_idx'), models.Index(fields=['employe', 'date'], name='presences_p_employe_789121_idx')],
                'unique_together': {('employe', 'date')},
            },
        ),
    ]
