# Generated by Django 6.0.5 on 2026-05-27 20:53

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('employes', '0003_ficheposte_departement_site_employe_banque_and_more'),
        ('sites_rh', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='RotationEquipe',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=100)),
                ('type_cycle', models.CharField(choices=[('3x8', '3×8 (rotation tri-équipe)'), ('2x12', '2×12 (rotation bi-équipe)'), ('5j8h', '5 jours / 8h'), ('6j8h', '6 jours / 8h'), ('personnalise', 'Personnalisé')], default='3x8', max_length=20)),
                ('description', models.TextField(blank=True)),
                ('duree_cycle_jours', models.IntegerField(default=21, help_text='Durée du cycle de rotation en jours')),
            ],
            options={
                'verbose_name': "Rotation d'équipe",
                'verbose_name_plural': "Rotations d'équipes",
            },
        ),
        migrations.CreateModel(
            name='TypeShift',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=100)),
                ('code', models.CharField(max_length=10, unique=True)),
                ('heure_debut', models.TimeField()),
                ('heure_fin', models.TimeField()),
                ('traverse_minuit', models.BooleanField(default=False, help_text='Vrai si shift 18h→06h')),
                ('duree_heures', models.DecimalField(decimal_places=2, default=8, max_digits=4)),
                ('est_nuit', models.BooleanField(default=False)),
                ('couleur', models.CharField(default='#6366f1', help_text='Couleur hex pour calendrier', max_length=7)),
                ('description', models.TextField(blank=True)),
            ],
            options={
                'verbose_name': 'Type de shift',
                'verbose_name_plural': 'Types de shifts',
            },
        ),
        migrations.CreateModel(
            name='Equipe',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=100)),
                ('code', models.CharField(max_length=10)),
                ('couleur', models.CharField(default='#10b981', max_length=7)),
                ('est_actif', models.BooleanField(default=True)),
                ('chef_equipe', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='equipes_dirigees', to='employes.employe')),
                ('site', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='equipes', to='sites_rh.site')),
                ('unite', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='sites_rh.unite')),
                ('rotation', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='equipes', to='planning.rotationequipe')),
            ],
            options={
                'verbose_name': 'Équipe',
                'verbose_name_plural': 'Équipes',
            },
        ),
        migrations.CreateModel(
            name='PlanningMensuel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('annee', models.IntegerField()),
                ('mois', models.IntegerField()),
                ('statut', models.CharField(choices=[('brouillon', 'Brouillon'), ('publie', 'Publié'), ('cloture', 'Clôturé')], default='brouillon', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('cree_par', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('site', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='plannings', to='sites_rh.site')),
            ],
            options={
                'verbose_name': 'Planning mensuel',
                'verbose_name_plural': 'Plannings mensuels',
                'unique_together': {('site', 'annee', 'mois')},
            },
        ),
        migrations.CreateModel(
            name='LignePlanning',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('type_jour', models.CharField(choices=[('travail', 'Jour travaillé'), ('repos', 'Repos'), ('conge', 'Congé'), ('ferie', 'Jour férié'), ('mission', 'Mission'), ('formation', 'Formation')], default='travail', max_length=20)),
                ('note', models.CharField(blank=True, max_length=200)),
                ('est_remplacement', models.BooleanField(default=False)),
                ('employe', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lignes_planning', to='employes.employe')),
                ('equipe', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='planning.equipe')),
                ('remplace_employe', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='remplacements_recus', to='employes.employe')),
                ('site_affecte', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='sites_rh.site')),
                ('planning', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lignes', to='planning.planningmensuel')),
                ('shift', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='planning.typeshift')),
            ],
            options={
                'verbose_name': 'Ligne planning',
                'verbose_name_plural': 'Lignes planning',
                'ordering': ['date', 'employe__nom'],
                'unique_together': {('planning', 'employe', 'date')},
            },
        ),
    ]
