# Generated by Django 6.0.5 on 2026-05-27 20:53

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employes', '0002_initial'),
        ('entreprises', '0001_initial'),
        ('sites_rh', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='FichePoste',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titre', models.CharField(max_length=150)),
                ('niveau', models.CharField(choices=[('operateur', 'Opérateur'), ('technicien', 'Technicien'), ('agent', 'Agent'), ('superviseur', 'Superviseur'), ('chef_equipe', "Chef d'équipe"), ('chef_service', 'Chef de service'), ('responsable', 'Responsable'), ('directeur', 'Directeur')], default='agent', max_length=30)),
                ('missions', models.TextField(blank=True)),
                ('responsabilites', models.TextField(blank=True)),
                ('competences_requises', models.TextField(blank=True)),
                ('formation_requise', models.CharField(blank=True, max_length=200)),
                ('experience_min_annees', models.IntegerField(default=0)),
                ('epi_requis', models.TextField(blank=True, verbose_name='EPI requis')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Fiche de poste',
                'verbose_name_plural': 'Fiches de poste',
            },
        ),
        migrations.AddField(
            model_name='departement',
            name='site',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='departements', to='sites_rh.site'),
        ),
        migrations.AddField(
            model_name='employe',
            name='banque',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='employe',
            name='contact_urgence_lien',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='employe',
            name='contact_urgence_nom',
            field=models.CharField(blank=True, max_length=150),
        ),
        migrations.AddField(
            model_name='employe',
            name='contact_urgence_telephone',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name='employe',
            name='date_expiration_cni',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='employe',
            name='device_id',
            field=models.CharField(blank=True, max_length=200, verbose_name='ID appareil mobile'),
        ),
        migrations.AddField(
            model_name='employe',
            name='device_imei',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='employe',
            name='entreprise',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='employes', to='entreprises.entreprise'),
        ),
        migrations.AddField(
            model_name='employe',
            name='groupe_sanguin',
            field=models.CharField(blank=True, max_length=5),
        ),
        migrations.AddField(
            model_name='employe',
            name='mode_paiement',
            field=models.CharField(choices=[('virement', 'Virement'), ('especes', 'Espèces'), ('mobile_money', 'Mobile Money')], default='virement', max_length=20),
        ),
        migrations.AddField(
            model_name='employe',
            name='nombre_enfants',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='employe',
            name='num_cni',
            field=models.CharField(blank=True, max_length=30, verbose_name='N° CNI/Passeport'),
        ),
        migrations.AddField(
            model_name='employe',
            name='numero_mobile_money',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name='employe',
            name='site',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='employes', to='sites_rh.site'),
        ),
        migrations.AddField(
            model_name='employe',
            name='situation_familiale',
            field=models.CharField(choices=[('celibataire', 'Célibataire'), ('marie', 'Marié(e)'), ('divorce', 'Divorcé(e)'), ('veuf', 'Veuf/Veuve')], default='celibataire', max_length=20),
        ),
        migrations.AddField(
            model_name='employe',
            name='telephone2',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name='employe',
            name='unite',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='employes', to='sites_rh.unite'),
        ),
        migrations.AlterField(
            model_name='employe',
            name='statut',
            field=models.CharField(choices=[('actif', 'Actif'), ('inactif', 'Inactif'), ('suspendu', 'Suspendu'), ('demissionnaire', 'Démissionnaire'), ('licencie', 'Licencié'), ('retraite', 'Retraité')], default='actif', max_length=20),
        ),
        migrations.AlterField(
            model_name='employe',
            name='type_contrat',
            field=models.CharField(choices=[('cdi', 'CDI'), ('cdd', 'CDD'), ('stage', 'Stage'), ('freelance', 'Freelance'), ('interimaire', 'Intérimaire')], default='cdi', max_length=20),
        ),
        migrations.CreateModel(
            name='AffectationHistorique',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_debut', models.DateField()),
                ('date_fin', models.DateField(blank=True, null=True)),
                ('motif', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('departement', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='employes.departement')),
                ('employe', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='historique_affectations', to='employes.employe')),
                ('poste', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='employes.poste')),
                ('site', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='sites_rh.site')),
                ('unite', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='sites_rh.unite')),
            ],
            options={
                'verbose_name': 'Historique affectation',
                'verbose_name_plural': 'Historiques affectations',
                'ordering': ['-date_debut'],
            },
        ),
        migrations.AddField(
            model_name='poste',
            name='fiche_poste',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='employes.ficheposte'),
        ),
    ]
