# Generated by Django 6.0.5 on 2026-05-28 14:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employes', '0003_ficheposte_departement_site_employe_banque_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='departement',
            name='code',
            field=models.CharField(blank=True, max_length=20),
        ),
    ]
