# Generated by Django 6.0.5 on 2026-05-28 15:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employes', '0004_add_code_to_departement'),
    ]

    operations = [
        migrations.AddField(
            model_name='ficheposte',
            name='horaires_applicables',
            field=models.TextField(blank=True, verbose_name='Horaires applicables'),
        ),
    ]
