# Generated by Django 6.0.5 on 2026-05-27 20:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('employes', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ElementSalaire',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=100)),
                ('type', models.CharField(choices=[('gain', 'Gain'), ('retenue', 'Retenue')], max_length=10)),
                ('taux', models.DecimalField(blank=True, decimal_places=4, max_digits=6, null=True)),
                ('montant_fixe', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('est_imposable', models.BooleanField(default=True)),
                ('est_actif', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Élément de salaire',
                'verbose_name_plural': 'Éléments de salaire',
            },
        ),
        migrations.CreateModel(
            name='BulletinPaie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('periode_debut', models.DateField()),
                ('periode_fin', models.DateField()),
                ('salaire_base', models.DecimalField(decimal_places=2, max_digits=12)),
                ('total_gains', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('total_retenues', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('salaire_brut', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('salaire_net', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('statut', models.CharField(choices=[('brouillon', 'Brouillon'), ('valide', 'Validé'), ('paye', 'Payé')], default='brouillon', max_length=20)),
                ('date_paiement', models.DateField(blank=True, null=True)),
                ('note', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('employe', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bulletins', to='employes.employe')),
            ],
            options={
                'verbose_name': 'Bulletin de paie',
                'verbose_name_plural': 'Bulletins de paie',
                'ordering': ['-periode_fin'],
                'unique_together': {('employe', 'periode_debut', 'periode_fin')},
            },
        ),
        migrations.CreateModel(
            name='LigneBulletin',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('base', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('taux', models.DecimalField(decimal_places=4, default=0, max_digits=6)),
                ('montant', models.DecimalField(decimal_places=2, max_digits=12)),
                ('bulletin', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lignes', to='paie.bulletinpaie')),
                ('element', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='paie.elementsalaire')),
            ],
        ),
    ]
