# Generated by Django 6.0.5 on 2026-05-27 20:53

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('entreprises', '0001_initial'),
        ('heures', '0001_initial'),
        ('paie', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='elementsalaire',
            options={'ordering': ['ordre_affichage', 'nom'], 'verbose_name': 'Élément de salaire', 'verbose_name_plural': 'Éléments de salaire'},
        ),
        migrations.AddField(
            model_name='bulletinpaie',
            name='cmu',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
        migrations.AddField(
            model_name='bulletinpaie',
            name='cotisation_cnps_employe',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
        migrations.AddField(
            model_name='bulletinpaie',
            name='cotisation_cnps_patronale',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
        migrations.AddField(
            model_name='bulletinpaie',
            name='deduction_absence',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
        migrations.AddField(
            model_name='bulletinpaie',
            name='genere_par',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='bulletinpaie',
            name='heures_dimanche',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=7),
        ),
        migrations.AddField(
            model_name='bulletinpaie',
            name='heures_ferie',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=7),
        ),
        migrations.AddField(
            model_name='bulletinpaie',
            name='heures_normales',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=7),
        ),
        migrations.AddField(
            model_name='bulletinpaie',
            name='heures_nuit',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=7),
        ),
        migrations.AddField(
            model_name='bulletinpaie',
            name='heures_supp_25',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=7),
        ),
        migrations.AddField(
            model_name='bulletinpaie',
            name='heures_supp_50',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=7),
        ),
        migrations.AddField(
            model_name='bulletinpaie',
            name='its',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='ITS/IRPP'),
        ),
        migrations.AddField(
            model_name='bulletinpaie',
            name='jours_absents',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='bulletinpaie',
            name='jours_travailles',
            field=models.IntegerField(default=26),
        ),
        migrations.AddField(
            model_name='bulletinpaie',
            name='mode_paiement',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name='bulletinpaie',
            name='montant_heures_ferie',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
        migrations.AddField(
            model_name='bulletinpaie',
            name='montant_heures_nuit',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
        migrations.AddField(
            model_name='bulletinpaie',
            name='montant_heures_supp',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
        migrations.AddField(
            model_name='bulletinpaie',
            name='recap_heures',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='heures.recapheures'),
        ),
        migrations.AddField(
            model_name='bulletinpaie',
            name='salaire_brut_imposable',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
        migrations.AddField(
            model_name='bulletinpaie',
            name='salaire_net_paye',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
        migrations.AddField(
            model_name='elementsalaire',
            name='categorie',
            field=models.CharField(choices=[('salaire_base', 'Salaire de base'), ('prime', 'Prime'), ('indemnite', 'Indemnité'), ('heure_supp', 'Heures supplémentaires'), ('heure_nuit', 'Heures de nuit'), ('heure_ferie', 'Heures fériées'), ('heure_dimanche', 'Heures dimanche'), ('transport', 'Transport'), ('panier', 'Panier repas'), ('logement', 'Logement'), ('conge_paye', 'Congé payé'), ('cnps', 'CNPS'), ('impot', 'Impôt (ITS/IRPP)'), ('cmu', 'CMU'), ('absence', 'Déduction absence'), ('avance', 'Avance sur salaire'), ('autre', 'Autre')], default='autre', max_length=30),
        ),
        migrations.AddField(
            model_name='elementsalaire',
            name='code',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name='elementsalaire',
            name='entreprise',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='entreprises.entreprise'),
        ),
        migrations.AddField(
            model_name='elementsalaire',
            name='est_soumis_cnps',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='elementsalaire',
            name='ordre_affichage',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='lignebulletin',
            name='quantite',
            field=models.DecimalField(decimal_places=2, default=1, max_digits=8),
        ),
        migrations.AlterField(
            model_name='bulletinpaie',
            name='statut',
            field=models.CharField(choices=[('brouillon', 'Brouillon'), ('valide', 'Validé'), ('paye', 'Payé'), ('annule', 'Annulé')], default='brouillon', max_length=20),
        ),
        migrations.AlterField(
            model_name='elementsalaire',
            name='taux',
            field=models.DecimalField(blank=True, decimal_places=4, help_text='% sur salaire base ou taux horaire', max_digits=8, null=True),
        ),
        migrations.AlterField(
            model_name='lignebulletin',
            name='taux',
            field=models.DecimalField(decimal_places=4, default=0, max_digits=8),
        ),
        migrations.CreateModel(
            name='JournalPaie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('periode_debut', models.DateField()),
                ('periode_fin', models.DateField()),
                ('total_salaires_bruts', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('total_cotisations_patronales', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('total_salaires_nets', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('nombre_bulletins', models.IntegerField(default=0)),
                ('statut', models.CharField(choices=[('en_cours', 'En cours'), ('valide', 'Validé'), ('cloture', 'Clôturé')], default='en_cours', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('bulletins', models.ManyToManyField(blank=True, to='paie.bulletinpaie')),
                ('cloture_par', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('entreprise', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='entreprises.entreprise')),
            ],
            options={
                'verbose_name': 'Journal de paie',
                'verbose_name_plural': 'Journaux de paie',
            },
        ),
    ]
