# Generated by Django 6.0.5 on 2026-05-27 20:53

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('employes', '0003_ficheposte_departement_site_employe_banque_and_more'),
        ('entreprises', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CategorieDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=100)),
                ('code', models.CharField(max_length=20, unique=True)),
                ('description', models.TextField(blank=True)),
                ('icone', models.CharField(default='file-text', max_length=50)),
            ],
            options={
                'verbose_name': 'Catégorie document',
                'verbose_name_plural': 'Catégories documents',
            },
        ),
        migrations.CreateModel(
            name='Document',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True)),
                ('fichier', models.FileField(upload_to='documents/%Y/%m/')),
                ('taille_fichier', models.IntegerField(default=0, help_text='Taille en octets')),
                ('type_mime', models.CharField(blank=True, max_length=100)),
                ('statut', models.CharField(choices=[('valide', 'Valide'), ('expire', 'Expiré'), ('en_attente', 'En attente validation'), ('archive', 'Archivé')], default='valide', max_length=20)),
                ('date_document', models.DateField(blank=True, null=True)),
                ('date_expiration', models.DateField(blank=True, help_text='Pour CNI, permis, etc.', null=True)),
                ('est_confidentiel', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('ajoute_par', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='documents_ajoutes', to=settings.AUTH_USER_MODEL)),
                ('categorie', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='documents.categoriedocument')),
                ('employe', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='employes.employe')),
                ('entreprise', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='entreprises.entreprise')),
            ],
            options={
                'verbose_name': 'Document',
                'verbose_name_plural': 'Documents',
                'ordering': ['-created_at'],
            },
        ),
    ]
