# Generated by Django 6.0.5 on 2026-05-27 20:34

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DemandeConge',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_debut', models.DateField()),
                ('date_fin', models.DateField()),
                ('nombre_jours', models.IntegerField()),
                ('motif', models.TextField(blank=True)),
                ('statut', models.CharField(choices=[('en_attente', 'En attente'), ('approuve', 'Approuvé'), ('refuse', 'Refusé'), ('annule', 'Annulé')], default='en_attente', max_length=20)),
                ('date_approbation', models.DateTimeField(blank=True, null=True)),
                ('commentaire_approbation', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Demande de congé',
                'verbose_name_plural': 'Demandes de congés',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='SoldeConge',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('annee', models.IntegerField()),
                ('jours_acquis', models.DecimalField(decimal_places=2, default=0, max_digits=6)),
                ('jours_pris', models.DecimalField(decimal_places=2, default=0, max_digits=6)),
                ('jours_restants', models.DecimalField(decimal_places=2, default=0, max_digits=6)),
            ],
            options={
                'verbose_name': 'Solde de congé',
                'verbose_name_plural': 'Soldes de congés',
            },
        ),
        migrations.CreateModel(
            name='TypeConge',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=100)),
                ('nombre_jours', models.IntegerField(default=0)),
                ('est_paye', models.BooleanField(default=True)),
                ('description', models.TextField(blank=True)),
            ],
            options={
                'verbose_name': 'Type de congé',
                'verbose_name_plural': 'Types de congés',
            },
        ),
    ]
