# Generated by Django 6.0.5 on 2026-05-27 20:34

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('conges', '0001_initial'),
        ('employes', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='demandeconge',
            name='approuve_par',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='conges_approuves', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='demandeconge',
            name='employe',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='demandes_conge', to='employes.employe'),
        ),
        migrations.AddField(
            model_name='soldeconge',
            name='employe',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='soldes_conge', to='employes.employe'),
        ),
        migrations.AddField(
            model_name='soldeconge',
            name='type_conge',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='conges.typeconge'),
        ),
        migrations.AddField(
            model_name='demandeconge',
            name='type_conge',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='conges.typeconge'),
        ),
        migrations.AlterUniqueTogether(
            name='soldeconge',
            unique_together={('employe', 'type_conge', 'annee')},
        ),
    ]
